<a href="https://colab.research.google.com/github/playdataJuhanKim/20230619colab/blob/main/ch05_01_numpy_%EA%B8%B0%EC%B4%88_%EA%B3%B5%EC%9C%A0%EC%9A%A9_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 배열(Array)
* 많은 데이터를 하나의 변수에 넣는 법? : **리스트**
* 하지만 리스트는...
    * 속도가 느리다
    * 메모리를 많이 차지한다

> 그래서? **배열(Array)**을 사용한다

* 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

## 특징
1. 모든 원소가 같은 **자료형**이어야 함
2. 원소의 갯수를 바꿀 수 없음(튜플과는 달리 원소를 바꿀 수 있음)

> 그런데 파이썬은 자체적으로 배열 자료형을 제공하지 않음<br>
> 그래서 우리는 **넘파이(Numpy)** 패키지를 import해서 사용

In [3]:
#colab과 anaconda에는 이미 numpy가 내장되어 있음
#import numpy #설치된 numpy를 가져온다.
#numpy는 np로 사용함. #imprt numpy as np (국룰)
import numpy as np

## 1차원 배열
* 리스트나 튜플처럼 한 줄로 이루어진 형태의 배열

In [2]:
np.array([1,2,3]) #실행문의 결과를 아래 블록에 표시해줌

array([1, 2, 3])

In [5]:
arr=np.array(range(0,10))
arr, type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [10]:
import random

def averagepython(n):
  '''n개의 랜덤한 0~1사이의 실수의 평균을 계산하는 함수'''
  s = 0
  for i in range(n):
    s+=random.random()
  return s / n

  averagepython(100,000)

In [16]:
%timeit averagepython(100_000)

12.6 ms ± 3.62 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
def average_numpy(n):
#'n개의 랜덤 0~1사이의 실수 numpy를 사용해서 평균내는 함수'
  s=np.random.random(n)
  return s.mean() #mean과 average

In [15]:
%timeit average_numpy(100_000)

1.11 ms ± 308 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


548 µs ± 6.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 벡터화 연산
* 배열 객체는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리**하는 벡터화 연산(vectorized operation)을 지원

In [18]:
data=list(range(0,10))

In [ ]:
#리스트에 +나 *를 사용하면 리스트가 연결되거나 배수만큼 늘어남.

In [22]:
%%time
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)
answer = []
for d in data:
  answer.append(d*2)
answer

CPU times: user 23 µs, sys: 1e+03 ns, total: 24 µs
Wall time: 27.9 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [23]:
%%timeit
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)
answer = []
for d in data:
  answer.append(d*2)
answer

942 ns ± 288 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
# 리스트 컴프리헨션
%%timeit
[d*2 for d in data]

597 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
# 벡터화 연산
arr=np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
%time arr*2

CPU times: user 48 µs, sys: 2 µs, total: 50 µs
Wall time: 52.7 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
%timeit arr*2

1.15 µs ± 77.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [32]:
# 리스트 객체에 정수를 곱하면 객체의 크기가 해당 정수 배만큼 증가
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

* 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [38]:
a=np.array(range(1,4))
b=np.array(range(10,40,10))
a , b

(array([1, 2, 3]), array([10, 20, 30]))

In [37]:
a*10

array([10, 20, 30])

In [39]:
a*12

array([12, 24, 36])

In [40]:
a == 2

array([False,  True, False])

In [42]:
a==3, b>10

(array([False, False,  True]), array([False,  True,  True]))

In [43]:
(a==3) & (b>10)

array([False, False,  True])

## 2차원 배열
* `ndarray`는 N-dimensional Array의 약자, 즉 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
* 2차원 배열 = 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열

* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성
    * 안쪽 리스트의 길이 : 행렬의 열의 수 (가로 크기)
    * 바깥쪽 리스트의 길이 : 행렬의 행의 수 (세로 크기)

In [45]:
arr=np.array([[0,1,2],[3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
# 행의 갯수, 열의 갯수
len(arr), len(arr[0]), len(arr[1])

(2, 3, 3)

## 💡 연습문제 1
> 아래 모양의 행렬 만들어 보기
```
10 20 30 40
50 60 70 80
```

In [50]:
arr=np.array([range(10,50,10), range(50, 90, 10)])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [51]:
arr=np.array([[1,2,3,4], [5,6,7,8]])*10
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
np.array([[(a * 4 + (b + 1)) * 10 for b in range(4)] for a in range(2)])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열

In [ ]:
# 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시
# m : matrix (2차원 배열, 행렬)
# t : three-dimention
t = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [11, 12, 13, 14],
            [15, 16, 17, 18],
            [19, 20, 21, 22],  # 4개
        ],  # 3개
    ]  # 가장 밖 리스트 -> 요소 2개
)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [ ]:
# 깊이, 행, 열


(2, 3, 4)

## 배열의 차원과 크기 알아내기
* `ndim`, `shape` **속성** 사용
> 속성 : 괄호 없이 이름만 써서 값을 호출

* `ndim` : 배열의 차원
* `shape` : 배열의 크기

In [53]:
a=np.array(range(1,4))
a

array([1, 2, 3])

In [55]:
a.ndim, a.shape

(1, (3,))

(2, (2, 3))

(3, (2, 3, 4))

## 배열의 복사
* copy와 view의 차이점은 copy는 새 배열(깊은 복사)이고 view는 원래 배열과 연결 되어 있다는 것(얕은 복사)
* copy는 데이터를 소유하며 copy에 대한 변경 사항은 원본 배열에 영향을 미치지 않으며 원본 배열에 대한 변경은 copy에 영향을 주지 않음
* view는 데이터를 소유하지 않으며 view에 대한 모든 변경 사항은 원래 배열에 영향을 미치고 원래 배열에 대한 모든 변경 사항은 보기에 영향을 줌

In [56]:
arr=np.array(range(1,5))
arr2=arr
arr[0]= 40
arr, arr2

(array([40,  2,  3,  4]), array([40,  2,  3,  4]))

In [57]:
arr=np.array(range(1,5))
arr2=arr.view() #일부러 원본과 연결된 사본을 만드는 것임.
arr[0]= 40
arr, arr2

(array([40,  2,  3,  4]), array([40,  2,  3,  4]))

In [60]:
arr=np.array(range(1,5))
arr2=arr.copy()
arr[0]= 40
arr, arr2

(array([40,  2,  3,  4]), array([1, 2, 3, 4]))

None
[1 2 3 4 5]


## 배열의 인덱싱

### 일차원 배열
* 리스트의 인덱싱과 같음

In [62]:
a=np.array(range(0,5))
print(a)
a[0], a[2]

[0 1 2 3 4]


(0, 2)

### 다차원 배열
* 콤마(comma, `,`)를 사용하여 접근
* 콤마로 구분된 차원을 축(axis)라고 함
    * like 그래프의 x축, y축

In [66]:
b=np.array([range(3), range(3,6)])
b, b.ndim, b.shape


(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [68]:
# b[0][0] #파이썬의 일반적인 방법
b[0,0] #넘파이의 기능(배열만 됨. 리스트에서는 안됨.)

0

In [70]:
b[0,1], b[-1, -1]

(1, 5)

5

## 배열 슬라이싱
* 다차원 배열의 원소 중 2개 이상의 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용

In [72]:
a=np.array([range(4), range(4,8)])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [74]:
#첫번째 행의 전체 열을 조회
print(a[0])
print(a[0,:])

[0 1 2 3]
[0 1 2 3]


In [75]:
#두 번째 열의 모든 행값? -> 일반적인 인덱싱으로는 힘듦.
a[:,1]

array([1, 5])

In [76]:
#두번째 행의 두번째 열부터 끝까지
a[1,1:]

array([5, 6, 7])

array([[0, 1],
       [4, 5]])

## 💡 연습문제 2

In [78]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
#@markdown (1) 값 7을 인덱싱
m[1,2]

7

In [90]:
#@markdown (2) 값 14을 인덱싱
m[2,4], m[-1,-1]

(14, 14)

In [86]:
#@markdown (3) 배열 [6,7]을 슬라이싱
m[1,1:3]

array([6, 7])

In [87]:
#@markdown (4) 배열 [7,12]을 슬라이싱
m[1:,2]

array([ 7, 12])

In [89]:
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱
m[:2, 3:5]

array([[3, 4],
       [8, 9]])

## 배열 인덱싱
* 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 받을 수 있음 (인덱스 배열)
* 일종의 조건 검색 기능

### 불리언 (Boolean) 배열 인덱싱
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

In [ ]:
# 짝수인 원소만 골라내고 싶다면?
# 짝수에 대응하는 곳에 True, 홀수에 대응하는 곳에 False


array([0, 2, 4, 6, 8])

In [ ]:
# 조건문 연산


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

array([0, 2, 4, 6, 8])

### 정수 배열 인덱싱
* 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수이여야 함

In [94]:
a=np.array(range(1,10))*11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

* 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음
* 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

In [96]:
#0,2,4,6,8번 인덱스에 있는 값을 가져오고 싶다면?
idx=np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [ ]:
idx=np.

### 다차원 배열에서의 배열 인덱싱

In [101]:
a=np.array([range(1,5),range(5,9),range(9,13)])
print(a)
a.ndim, a.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(2, (3, 4))

In [103]:
a[:,[0,3]], a[:,[True, False, False, True]], a[]

(array([[ 1,  4],
        [ 5,  8],
        [ 9, 12]]),
 array([[ 1,  4],
        [ 5,  8],
        [ 9, 12]]))

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 💡 연습문제 3

In [105]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [107]:
# (1) 3의 배수 찾기
print(x[x % 3 == 0])


[ 3  6  9 12 15 18]


In [108]:
# (2) 4로 나누면 1이 남는 수 찾기
print(x[x%4==1])

[ 1  5  9 13 17]


In [111]:
# (3) 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
print(x[(x%3==0) & (x%4 == 1)])

[9]


## 배열 검색

In [ ]:
arr=np,arra

(array([3, 5, 6]),)

(array([1, 3, 5, 7]),)